name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install and build
        run: |
          npm install
          npm run build --if-present
      - name: Store artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          if-no-files-found: error
          path: dist/es6

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: npm start
          wait-on: 'http://localhost:8080'

      - name: Upload Cypress artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress
          path: |
            cypress/snapshots
            cypress/videos
          if-no-files-found: error

      - name: Run image diff
        run: npm run cypress:diff:ci



